---
title: "Team"
---

Decision Intelligence 4 Health is a collaborative project to improve the real-time decision making of public health agencies, and other health and human services organizations. 

## Lead

- [Tom치s Arag칩n](https://substack.com/@tomasaragon), [TEAM Public Health](https://teampublichealth.substack.com/) and UC Berkeley Public Health. 

## Collaborators / Contributors (in alphabetical order)

- Gilda Zarate-Gonzalez, Decision Intelligence Section, CDPH[^CDPH]
- Hector Manuel Sanchez Castellanos, Decision Intelligence Section, CDPH
- Lauren White, Decision Intelligence Section, CDPH
- Lisa Bandong, Office of Planning & Planning, CDPH
- Natalie Linton, Decision Intelligence Section, CDPH
- Phoebe Lu, Decision Intelligence Section, CDPH 
- Tom치s Le칩n, Decision Intelligence Section, CDPH

## Acknowledgments (in alphabetical order) 

- [Annie Duke, author, speaker, and consultant](https://www.annieduke.com/) 
- [Doug Owens, Stanford University](https://med.stanford.edu/profiles/douglas-owens)[^OwensBook] 
- [Joshua Solomon, Stanford University](https://healthpolicy.fsi.stanford.edu/people/joshua-salomon)  


[^CDPH]: California Department of Public Health

[^OwensBook]:  Sox, Harold C., Michael C. Higgins, Douglas K. Owens, and Gillian Sanders Schmidler. *Medical Decision Making*. 3rd ed. John Wiley & Sons, Inc, 2024. https://doi.org/10.1002/9781119627876.

